SELECT 
DB_NAME() AS 'Current Database',
BU.name as ClientBusinessName,
 [LoosePart].[Id] AS [Id]
,[LoosePart].[Code] AS [Code]
,[Table1].[Code] AS [BaseUnitOfMeasureCode]
,[Table2].[Text] AS [BaseUnitOfMeasureCodeTranslation]
,[LoosePart].[Length] AS [Length]
,[LoosePart].[Width] AS [Width]
,[LoosePart].[Height] AS [Height]
,cast(replace([LoosePart].[Weight],',','.') as float) AS [Weight]
,[LoosePart].[Volume] AS [Volume]
,[LoosePart].[Surface] AS [Surface]
,[LoosePart].[BaseArea] AS [BaseArea]
,[LoosePart].[LotNo] AS [LotNo]
,[LoosePart].[SerialNo] AS [SerialNo]
,[LoosePart].[WarrantyDate] AS [WarrantyDate]
,[LoosePart].[ExpirationDate] AS [ExpirationDate]
,[LoosePart].[Description] AS [Description]
,[Table3].[Name] AS [StatusName]
,[Table4].[Text] AS [StatusNameTranslation]
,[Table3].[Color] AS [StatusColor]
,[Table5].[CreatedMAX] AS [LastStatusChange]
,[Table6].[Name] AS [ActualLocationName]
,[Table7].[Name] AS [ActualZoneName]
,[Table8].[Code] AS [ActualBinCode]
,[Table9].[Code] AS [ActualHandlingUnitCode]
,[Table10].[Code] AS [TopHandlingUnitCode]
,[Table11].[Code] AS [ShipmentHeaderCode]
,[Table12].[QuantityBase] AS [Quantity]
,bu.id AS [CustomerBusinessUnitId]
,[LoosePart].[Updated] AS [Updated]
,[Table330].[Content] AS [Datum WE (fix)]
,[Table331].[Content] AS [SBExport]
,[Table332].[Content] AS [Shockindicatoren]
,[Table333].[Content] AS [Kennwort]
,[Table334].[Content] AS [Painting Colour]
,[Table335].[Content] AS [Luftfracht]
,[Table336].[Content] AS [lpShipmentBlocked]
,[Table337].[Content] AS [Lackschaden]
,[Table338].[Content] AS [Schutzklasse]
,[Table339].[Content] AS [Feld Nr.]
,[Table340].[Content] AS [Verpackungssperre]
,[Table341].[Content] AS [Sperrlager Gründe]
,[Table342].[Content] AS [Liefertermin Intern]
,[Table343].[Content] AS [Damage description]
,[Table344].[Content] AS [Liefertermin Extern]
,[Table345].[Content] AS [Insp. OK]
,[Table346].[Content] AS [Fotodoku]
,[Table347].[Content] AS [Abrechnungskategorie]
,[Table348].[Content] AS [LKW Kennz.]
,[Table349].[Content] AS [VVID]
,[Table350].[Content] AS [Verpackungsart]
,[Table351].[Content] AS [Kommentar]
,[Table352].[Content] AS [VVBIN]
,[Table353].[Content] AS [Shockrecorder]
,[Table354].[Content] AS [Position]
,cast(replace([Table355].[Content],',','.') as float) AS [Brutto kg]
,[Table356].[Content] AS [Insp. Geplant]
,[Table357].[Content] AS [Produktlinie]
,[Table146].[Content] AS [Poject]
,[Table146].[Entity] AS [Entity]
 FROM [LoosePart] AS [LoosePart] 
 left join BusinessUnitPermission BUP on LoosePart.id = BUP.LoosePartId
 left join BusinessUnit BU on BUP.BusinessUnitID = BU.id
left outer JOIN [UnitOfMeasure] AS [Table1] ON [Table1].[Id] = [LoosePart].[BaseUnitOfMeasureId] 
left outer JOIN [Translation] AS [Table2] ON [Table2].[EntityId] = [LoosePart].[BaseUnitOfMeasureId] and [Table2].[Entity] ='21' and [Table2].[Column] = 'Code' and [Table2].[Language] = 'de' 
left outer JOIN [Status] AS [Table3] ON [Table3].[Id] = [LoosePart].[StatusId] 
left outer JOIN [Translation] AS [Table4] ON [Table4].[EntityId] = [LoosePart].[StatusId] and [Table4].[Entity] = '27' and [Table4].[Column] = 'Name' and [Table4].[Language] = 'de' 
left outer JOIN(SELECT EntityId,MAX([Created]) AS [CreatedMAX] FROM [WorkflowEntry] WHERE [Entity] = '15' GROUP BY EntityId) AS [Table5] ON [Table5].[EntityId] = [LoosePart].[Id]
left outer JOIN [Location] AS [Table6] ON [Table6].[Id] = [LoosePart].[ActualLocationId] 
left outer JOIN [Zone] AS [Table7] ON [Table7].[Id] = [LoosePart].[ActualZoneId] 
left outer JOIN [Bin] AS [Table8] ON [Table8].[Id] = [LoosePart].[ActualBinId] 
left outer JOIN [HandlingUnit] AS [Table9] ON [Table9].[Id] = [LoosePart].[ActualHandlingUnitId] 
left outer JOIN [HandlingUnit] AS [Table10] ON [Table10].[Id] = [LoosePart].[TopHandlingUnitId] 
left outer JOIN [ShipmentHeader] AS [Table11] ON [Table11].[Id] = [LoosePart].[ShipmentHeaderId] 
INNER JOIN [WarehouseContent] AS [Table12] ON  ([Table12].[LoosePartId] = [LoosePart].[Id] OR ([Table12].[LoosePartId] IS NULL AND [LoosePart].[Id] IS NULL)) AND  ([Table12].[LocationId] = [LoosePart].[ActualLocationId] OR ([Table12].[LocationId] IS NULL AND [LoosePart].[ActualLocationId] IS NULL)) AND  ([Table12].[ZoneId] = [LoosePart].[ActualZoneId] OR ([Table12].[ZoneId] IS NULL AND [LoosePart].[ActualZoneId] IS NULL)) AND  ([Table12].[BinId] = [LoosePart].[ActualBinId] OR ([Table12].[BinId] IS NULL AND [LoosePart].[ActualBinId] IS NULL)) 
INNER JOIN [CustomField] AS [Table30] ON [Table30].[ClientBusinessUnitId] = bup.[BusinessUnitId] AND [Table30].[Name] = 'Datum WE (fix)' INNER JOIN [CustomValue] AS [Table330] ON [Table330].[CustomFieldId] = [Table30].[Id] AND [Table330].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table31] ON [Table31].[ClientBusinessUnitId] = bup.[BusinessUnitId] AND [Table31].[Name] = 'SBExport' INNER JOIN [CustomValue] AS [Table331] ON [Table331].[CustomFieldId] = [Table31].[Id] AND [Table331].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table32] ON [Table32].[ClientBusinessUnitId] = bup.[BusinessUnitId] AND [Table32].[Name] = 'Shockindicatoren' INNER JOIN [CustomValue] AS [Table332] ON [Table332].[CustomFieldId] = [Table32].[Id] AND [Table332].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table33] ON [Table33].[ClientBusinessUnitId] = bup.[BusinessUnitId] AND [Table33].[Name] = 'Kennwort' INNER JOIN [CustomValue] AS [Table333] ON [Table333].[CustomFieldId] = [Table33].[Id] AND [Table333].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table34] ON [Table34].[ClientBusinessUnitId] = bup.[BusinessUnitId] AND [Table34].[Name] = 'Painting Colour' INNER JOIN [CustomValue] AS [Table334] ON [Table334].[CustomFieldId] = [Table34].[Id] AND [Table334].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table35] ON [Table35].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table35].[Name] = 'Luftfracht' INNER JOIN [CustomValue] AS [Table335] ON [Table335].[CustomFieldId] = [Table35].[Id] AND [Table335].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table36] ON [Table36].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table36].[Name] = 'lpShipmentBlocked' INNER JOIN [CustomValue] AS [Table336] ON [Table336].[CustomFieldId] = [Table36].[Id] AND [Table336].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table37] ON [Table37].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table37].[Name] = 'Lackschaden' INNER JOIN [CustomValue] AS [Table337] ON [Table337].[CustomFieldId] = [Table37].[Id] AND [Table337].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table38] ON [Table38].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table38].[Name] = 'Schutzklasse' INNER JOIN [CustomValue] AS [Table338] ON [Table338].[CustomFieldId] = [Table38].[Id] AND [Table338].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table39] ON [Table39].[ClientBusinessUnitId] = bup.[BusinessUnitId] AND [Table39].[Name] = 'Feld Nr.' INNER JOIN [CustomValue] AS [Table339] ON [Table339].[CustomFieldId] = [Table39].[Id] AND [Table339].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table40] ON [Table40].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table40].[Name] = 'Verpackungssperre' INNER JOIN [CustomValue] AS [Table340] ON [Table340].[CustomFieldId] = [Table40].[Id] AND [Table340].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table41] ON [Table41].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table41].[Name] = 'Sperrlager Gründe' INNER JOIN [CustomValue] AS [Table341] ON [Table341].[CustomFieldId] = [Table41].[Id] AND [Table341].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table42] ON [Table42].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table42].[Name] = 'Liefertermin Intern' INNER JOIN [CustomValue] AS [Table342] ON [Table342].[CustomFieldId] = [Table42].[Id] AND [Table342].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table43] ON [Table43].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table43].[Name] = 'Damage description' INNER JOIN [CustomValue] AS [Table343] ON [Table343].[CustomFieldId] = [Table43].[Id] AND [Table343].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table44] ON [Table44].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table44].[Name] = 'Liefertermin Extern' INNER JOIN [CustomValue] AS [Table344] ON [Table344].[CustomFieldId] = [Table44].[Id] AND [Table344].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table45] ON [Table45].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table45].[Name] = 'Insp. OK' INNER JOIN [CustomValue] AS [Table345] ON [Table345].[CustomFieldId] = [Table45].[Id] AND [Table345].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table46] ON [Table46].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table46].[Name] = 'Fotodoku' INNER JOIN [CustomValue] AS [Table346] ON [Table346].[CustomFieldId] = [Table46].[Id] AND [Table346].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table47] ON [Table47].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table47].[Name] = 'Abrechnungskategorie' INNER JOIN [CustomValue] AS [Table347] ON [Table347].[CustomFieldId] = [Table47].[Id] AND [Table347].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table48] ON [Table48].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table48].[Name] = 'LKW Kennz.' INNER JOIN [CustomValue] AS [Table348] ON [Table348].[CustomFieldId] = [Table48].[Id] AND [Table348].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table49] ON [Table49].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table49].[Name] = 'VVID' INNER JOIN [CustomValue] AS [Table349] ON [Table349].[CustomFieldId] = [Table49].[Id] AND [Table349].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table50] ON [Table50].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table50].[Name] = 'Verpackungsart' INNER JOIN [CustomValue] AS [Table350] ON [Table350].[CustomFieldId] = [Table50].[Id] AND [Table350].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table51] ON [Table51].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table51].[Name] = 'Kommentar' INNER JOIN [CustomValue] AS [Table351] ON [Table351].[CustomFieldId] = [Table51].[Id] AND [Table351].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table52] ON [Table52].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table52].[Name] = 'VVBIN' INNER JOIN [CustomValue] AS [Table352] ON [Table352].[CustomFieldId] = [Table52].[Id] AND [Table352].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table53] ON [Table53].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table53].[Name] = 'Shockrecorder' INNER JOIN [CustomValue] AS [Table353] ON [Table353].[CustomFieldId] = [Table53].[Id] AND [Table353].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table54] ON [Table54].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table54].[Name] = 'Position' INNER JOIN [CustomValue] AS [Table354] ON [Table354].[CustomFieldId] = [Table54].[Id] AND [Table354].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table55] ON [Table55].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table55].[Name] = 'Brutto kg' INNER JOIN [CustomValue] AS [Table355] ON [Table355].[CustomFieldId] = [Table55].[Id] AND [Table355].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table56] ON [Table56].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table56].[Name] = 'Insp. Geplant' INNER JOIN [CustomValue] AS [Table356] ON [Table356].[CustomFieldId] = [Table56].[Id] AND [Table356].[EntityId] = [LoosePart].[Id]
INNER JOIN [CustomField] AS [Table57] ON [Table57].[ClientBusinessUnitId] =  bup.[BusinessUnitId] AND [Table57].[Name] = 'Produktlinie' INNER JOIN [CustomValue] AS [Table357] ON [Table357].[CustomFieldId] = [Table57].[Id] AND [Table357].[EntityId] = [LoosePart].[Id]
INNER JOIN (SELECT edvr.[EntityId], dv.[Content], edvr.[Entity] 
	FROM [DimensionValue] AS dv INNER JOIN [EntityDimensionValueRelation] AS edvr ON (edvr.[DimensionValueId] = dv.id) 
WHERE (dv.[DimensionId] = '78212081-d8d5-40ef-9e22-78702c976f1e')) AS [Table146] ON ([LoosePart].[Id] = [Table146].[EntityId]) AND ([Table146].[Entity] = '15')
and ( bup.[BusinessUnitId] = $P{ClientBusinessUnitID} )
and $X{IN, [LoosePart].[Id], LoosePartIDs}