

SELECT  [Id]
      ,[UserId]
      ,[ProfileObject]
      ,[CreatedById]
      ,[UpdatedById]
      ,[Created]
      ,[Updated]
      ,case [Form]
      when 1 then 'ZoneListViewModel'
when 2 then 'LoosePartListViewModel'
when 3 then 'LocationListViewModel'
when 4 then 'BinListViewModel'
when 5 then 'HandlingUnitTypeListViewModel'
when 6 then 'CustomFieldListViewModel'
when 7 then 'BusinessUnitListViewModel'
when 8 then 'DataTypeListViewModel'
when 9 then 'DimensionListViewModel'
when 10 then 'DimensionFieldListViewModel'
when 11 then 'PermissionListViewModel'
when 12 then 'RoleListViewModel'
when 13 then 'StatusListViewModel'
when 14 then 'UnitOfMeasureListViewModel'
when 15 then 'HandlingUnitListViewModel'
when 16 then 'UserListViewModel'
when 17 then 'WorkflowListViewModel'
when 18 then 'AddressListViewModel'
when 19 then 'DimensionValueListViewModel'
when 20 then 'LoosePartIdentifierListViewModel'
when 21 then 'LoosePartUnitOfMeasureListViewModel'
when 22 then 'WarehouseEntryListViewModel'
when 23 then 'WarehouseContentListViewModel'
when 25 then 'LoosePartPackListViewModel'
when 26 then 'UnpackListViewModel'
when 27 then 'HandlingUnitPackListViewModel'
when 30 then 'WarehouseContentForLoosePartListViewModel'
when 31 then 'WarehouseContentForHandlingUnitListViewModel'
when 32 then 'WarehouseContentForLocationListViewModel'
when 33 then 'WarehouseContentForZoneListViewModel'
when 34 then 'WarehouseContentForBinListViewModel'
when 35 then 'PackingRuleListViewModel'
when 37 then 'StatusFilterListViewModel'
when 38 then 'DisplayUOMListViewModel'
when 39 then 'ShipmentHeaderListViewModel'
when 40 then 'ShipmentLineListViewModel'
when 41 then 'LoosePartLoadListViewModel'
when 42 then 'UnloadListViewModel'
when 43 then 'HandlingUnitLoadListViewModel'
when 44 then 'DocumentTemplateListViewModel'
when 45 then 'PackingOrderHeaderListViewModel'
when 46 then 'PackingOrderLineListViewModel'
when 47 then 'LoosePartPackingOrderListViewModel'
when 48 then 'HandlingUnitPackingOrderListViewModel'
when 49 then 'InventoryHeaderListViewModel'
when 50 then 'InventoryLineListViewModel'
when 51 then 'ShipmentHeaderLoadingListViewModel'
when 52 then 'ShipmentHeaderUnloadingListViewModel'
when 53 then 'BCSActionListViewModel'
when 56 then 'NumberSeriesListViewModel'
when 57 then 'RolePermissionListViewModel'
when 58 then 'BusinessUnitRelationViewModel'
when 59 then ' DocumentTemplateSubreportListViewModel'
when 60 then 'AssignRolePermissionListViewModel'
when 61 then 'AssignBusinessUnitRelationViewModel'
when 62 then 'AssignDocumentTemplateSubreportListViewModel'
when 65 then 'BCSActionPermissionListViewModel'
when 66 then 'BCSActionAssignPermissionListViewModel'
when 67 then 'UserRoleListViewModel'
when 68 then 'Log4NetListViewModel'
when 69 then 'CommentListViewModel'
when 70 then 'ServiceTypeListViewModel'
when 71 then 'ServiceLineListViewModel'
when 72 then 'LogEntityListViewModel'
when 73 then 'ComponentListViewModel'
when 74 then 'EntityDevicePlacementListViewModel'
when 75 then 'TrackingMessageListViewModel'
when 76 then 'BusinessUnitPermissionListViewModel'
when 77 then 'HandlingUnitIdentifierListViewModel'
when 78 then 'LocationUtilisationListViewModel'
when 79 then 'BCSLogListViewModel'
when 80 then 'ReportingListViewModel'
end as Form
      ,[DimensionId]
  FROM [DFCZ_OSLET].[dbo].[UserProfile]
  --where UserId = (select id from [User] where login = 'alexander.dick')