DECLARE @CUSTOMFIELDID as VARCHAR(250)
DECLARE @CUSTOMFIELDNAME as VARCHAR(250)
DECLARE @CLIENT as VARCHAR (250)

BEGIN TRANSACTION

DECLARE CUSTOM_FIELD CURSOR FOR 
select 

CF.id, CF.Name, BU.Name from DFCZ_OSLET.dbo.customfield CF with (NOLOCK) 
inner join BusinessUnit BU with (NOLOCK) on CF.ClientBusinessUnitId = BU.id and BU.[Type] = 2 

where CF.visible = 0
group by CF.id,CF.Name, BU.Name order by BU.NAME, CF.Name

OPEN CUSTOM_FIELD;
FETCH NEXT FROM CUSTOM_FIELD INTO @CUSTOMFIELDID,@CUSTOMFIELDNAME,@CLIENT;
WHILE @@FETCH_STATUS = 0  
    BEGIN 

PRINT '=== DELETE CUSTOM FIELD VALUE MAPPING: ['+@CUSTOMFIELDNAME+'] IN CLIENT: ['+@CLIENT+'] ===';
delete from CustomFieldValueMapping where CustomFieldId = @CUSTOMFIELDID 
PRINT '=== DELETE CUSTOM VALUES FROM FIELD: ['+@CUSTOMFIELDNAME+'] IN CLIENT: ['+@CLIENT+'] ===';
delete from CustomFieldValue where CustomFieldId = @CUSTOMFIELDID
PRINT '=== DELETE CUSTOM FIELD: ['+@CUSTOMFIELDNAME+'] IN CLIENT: ['+@CLIENT+'] ===';
delete from CustomField where Id = @CUSTOMFIELDID

FETCH NEXT FROM CUSTOM_FIELD INTO @CUSTOMFIELDID,@CUSTOMFIELDNAME,@CLIENT;
END;
CLOSE CUSTOM_FIELD;
DEALLOCATE CUSTOM_FIELD;
 
 ROLLBACK